### ISSUE TITLE
the training data

### ISSUE THREAD

**Issue by framsc** [DerekWang96/pytorch-speech2vec#1]
The code seems great. Could you please share the training data in Google drive? or give some infomation about how to create it?

**Comment by ZhanpengWang96** [comment]
Hi! You can check the get_word_segmentations.py file I just updated, which is for generating the pickle file needed in the Speech2Vec.ipynb file, both for training and the generating of word vectors.  As for the alignment files for librispeech, you can download them in this repo: https://github.com/CorentinJ/librispeech-alignments.

**Comment by framsc** [comment]
Thank you very much!
